"""auto-vote

Revision ID: aaf023d0d3b1
Revises: bebac2865bb4
Create Date: 2023-06-17 13:22:05.218412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aaf023d0d3b1'
down_revision = 'bebac2865bb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('posts_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['posts_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('users_id', 'posts_id')
    )
    op.drop_table('check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check',
    sa.Column('cret_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.drop_table('votes')
    # ### end Alembic commands ###
